name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Suggest a new feature or improvement to existing functionality.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Feature importance
      options:
        - P0 (Critical - Blocking business goals)
        - P1 (High - Significant value)
        - P2 (Medium - Nice to have)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Feature category
      options:
        - revenue (Direct revenue impact)
        - growth (User/customer acquisition)
        - ops (Operational efficiency)
        - security (Security enhancement)
        - docs (Documentation)
        - research (Research/exploration)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a user, I want to... so that I can..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "Describe your ideal solution"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions did you consider?
      placeholder: "Other approaches you've thought about"
    validations:
      required: false

  - type: textarea
    id: value
    attributes:
      label: Business Value
      description: Why should we build this? What's the impact?
      placeholder: |
        - Revenue impact: +€X/month
        - Time saved: X hours/week
        - User satisfaction: High/Medium/Low
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Success Criteria
      description: How will we know this is successful?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Performance is acceptable
        - [ ] Users can complete task X
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples, or references?
      placeholder: "Add screenshots, links, or examples"
    validations:
      required: false
